# Generated by Django 4.2.5 on 2023-09-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_pending',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
