# Generated by Django 4.2.5 on 2023-09-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_alter_robot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='sold',
            field=models.DateTimeField(null=True),
        ),
    ]
